HW2_A_SangMinPark: main.o input.o calc.o output.o linkedlist.o datahandling.o
	gcc -o HW2_A_SangMinPark main.o input.o calc.o output.o linkedlist.o datahandling.o
main.o: main.c
	gcc -c main.c
input.o: input.c
	gcc -c input.c
calc.o: calc.c
	gcc -c calc.c
output.o: output.c
	gcc -c output.c
linkedlist.o: linkedlist.c
	gcc -c linkedlist.c
datahandling.o: datahandling.c
	gcc -c datahandling.c
